Feature/onse
tkato-89024/GeneralModule_Android pull request #2
Opened 2020-01-29 09:30 UTC by ao-clouds

ArrayUtilTest,StringUtilTestを記載しました。

2020-01-29 22:07 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/ArrayUtilTest.java
> +    }
テストに関係なくて細かい部分ですが、
} と // endregion reverse の間を一行空けてください。

2020-01-29 22:58 UTC, tkato-89024 requested changes
ひとまず気になったところ全てに細かくコメント記載しました。
確認してください。

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/ArrayUtilTest.java
> +    }
テストに関係なくて細かい部分ですが、
} と // endregion reverse の間を一行空けてください。

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/ArrayUtilTest.java
> +    }
テストに関係なくて細かい部分ですが、
メソッドの最後と、次のメソッドの間（} と @Test の間）を一行空けてください。

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/ArrayUtilTest.java
> +    @Test
テストに関係なくて細かい部分ですが、
メソッドの最後と、次のメソッドの間（} と @Test の間）を一行空けてください。

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/build.gradle
> +}
// region maven repositories 〜 // endregion maven repositories の間にある内容は、
GeneralModule をライブラリとして扱うためのファイル書き出しに使用しているものです。

143 ~ 147 行の内容がそれと関係なければ、region の外にまとめてください

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/build.gradle
> +apply from: './jacoco.gradle'
143 ~ 147 行目の内容が jacoco の内容であれば、
region で囲って記述お願いします。

記述例
```suggestion
// endregion maven repositories

// region jacoco (code coverage option)

// コンパイル時に使用する文字コードをUTF-8で固定する
tasks.withType(AbstractCompile).each { it.options.encoding = 'UTF-8' }
tasks.withType(Test) {
    systemProperty "file.encoding", "UTF-8"
}

apply from: './jacoco.gradle' 

// endregion jacoco (code coverage option)
```

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/build.gradle
> +    }
調べたら、これは InstrumentedTest で Context が使えない時に記述する内容のようですが、
これがなくても下の記述で Context は使えていると考えていました。
```java
// ApplicationContext
Context appContext = InstrumentationRegistry.getInstrumentation().getTargetContext();

// Activity
// public 以外だとエラー
@Rule
public ActivityScenarioRule<PermissionerTestActivity> rule = new ActivityScenarioRule<>(PermissionerTestActivity.class);
```
includeAndroidResources の記述は本当にいりますか？

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/StringUtilTest.java
> +
test_isDigit の assertFalse の記述位置が、assertTrue を挟んだ形になっています。
```
        assertFalse(StringUtil.isDigit(""));

        assertTrue(StringUtil.isDigit("12345"));
        assertTrue(StringUtil.isDigit("098765"));

        assertFalse(StringUtil.isDigit("-1234"));
        assertFalse(StringUtil.isDigit("+1234"));
        assertFalse(StringUtil.isDigit("1.234"));
```
True と False の記述はそれぞれまとめて記述したほうがよくないですか？

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/StringUtilTest.java
> +
test_isDigit と同じく、test_isNumeric の assertFalse の記述位置が、assertTrue を挟んだ形になっています。

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/jacoco.gradle
> +}
build.gradle でのバージョン整理はできませんか？
```
ext.versions = [
    'appcompat':   '1.1.0', // androidx
    'junit':       '4.12',
    'junitTest':   '1.1.1',
    'espresso':    '3.2.0',
    'jacoco':      '0.8.4',
    'timber':      '4.7.1',
    'jackson':     '2.4.4',
]
```

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/build.gradle
> +    testImplementation 'org.robolectric:robolectric:4.3'
このライブラリ導入は、includeAndroidResources と共に導入したと考えていますが、
このライブラリが必要な場合、お願いが２つあります。

1. バージョンを別の build.gradle で管理してください
```
testImplementation ("org.robolectric:robolectric:${versions.robolectric}")

ext.versions = [
    'appcompat':   '1.1.0', // androidx
    'junit':       '4.12',
    'junitTest':   '1.1.1',
    'espresso':    '3.2.0',
    'robolectric': '4.3',
    'timber':      '4.7.1',
    'jackson':     '2.4.4',
]
```
2. テストのライブラリは上のほうでまとめているので、
上でまとめてください
```
    implementation ("androidx.appcompat:appcompat:${versions.appcompat}")
    testImplementation ("junit:junit:${versions.junit}")
    androidTestImplementation ("androidx.test.ext:junit:${versions.junitTest}")
    androidTestImplementation ("androidx.test.espresso:espresso-core:${versions.espresso}")
    testImplementation ("org.robolectric:robolectric:${versions.robolectric}") // includeAndroidResources の使用
```

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/StringUtilTest.java
> +import org.junit.Assert;
おそらく使用していない import が残っています。
import を削除してください。

AndroidStudio では自動インポートの設定ができるので、検索して設定すると多少補完してくれると思います。
それでも import 文が残る場合は、インポートの最適化のショートカットを使うことで、使用していない import を削除してくれるので、コードを書いた後は確認してください。

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/StringUtilTest.java
> +        assertArrayEquals(resultValue, StringUtil.split(str1,null));
このファイルを AndroidStudio で確認した時、警告文がでてると思います。
警告文が出ている場合、スクロールバーが黄色くなっていると思うので、
全体的にスクロールバーから黄色い表示がなくなるように修正してください。

この行の警告文は、テスト用にあえて書いている引数によって警告がでているので、
「あえてそういった引数を書いているので警告はいりません」というアノテーションを記載することで
警告を出さないようにしてください。

2020-01-29 22:58 UTC, tkato-89024 commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/ArrayUtilTest.java
> +            assertTrue(resultValue.get(i) == list[i]);
このファイルを AndroidStudio で確認した時、警告文がでてると思います。
警告文が出ている場合、スクロールバーが黄色くなっていると思うので、
全体的にスクロールバーから黄色い表示がなくなるように修正してください。

この行の警告文は、jUnit のライブラリが出している警告なので
一度警告文を読んで修正してみてください。

2020-01-30 01:37 UTC, ao-clouds commented on general-module/build.gradle
> +}
ありがとうございます。このコード自体が不要なので削除したいと思います(もともとカバレッジレポートの文字化けを修正しようとしてましたが、これでも直ってないため)

2020-01-30 01:44 UTC, ao-clouds commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/StringUtilTest.java
> +
Nullのパターンだけ無意味に隔離してました。。確かにFalse同士でまとめたほうがわかりやすいので、そうします。

2020-01-30 01:45 UTC, ao-clouds commented on general-module/src/test/java/jp/co/model/tkato/general_module/util/StringUtilTest.java
> +
同じく、FalseはFalseでまとめます。

2020-01-30 02:21 UTC, ao-clouds commented on general-module/build.gradle
> +    }
不要なので削除します。

2020-01-30 02:30 UTC, ao-clouds commented on general-module/jacoco.gradle
> +}
build.gradleにまとめます。

2020-01-30 02:36 UTC, ao-clouds commented on general-module/build.gradle
> +    testImplementation 'org.robolectric:robolectric:4.3'
includeAndroidResouces自体が不要なので、行削除します。ライブラリの追加については承知しました。

2020-01-30 08:13 UTC, tkato-89024 approved these changes

2020-01-30 08:14 UTC, merged